version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Unit Tests
          command: gradle test
      - run:
          name: Integration Tests
          command: gradle integrationTest
      - run:
          name: Generate Code Coverage Report
          command: gradle jacocoTestReport
      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash)
